name: Bump go4.org/unsafe/assume-no-moving-gc

on:
  push:
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  bump:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Install Nix shell
        uses: diamondburned/cache-install@main
        with:
          shell-file: shell.nix

      - name: Bump go4.org/unsafe/assume-no-moving-gc
        run: |
          (
            cd pkg
            go get -u go4.org/unsafe/assume-no-moving-gc
            go mod tidy
          )

      - name: Tidy up Go modules
        run: |
          go mod tidy
          go work sync

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump go4.org/unsafe/assume-no-moving-gc
